config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recordings

  get '/tv/index'
  get '/tv/banner'

  get '/tv/current', to: 'tracks#current'

  resources :playlists do
    resources :tracks
  end

  root to: 'tv#index'
end

app/controllers/tv_controller.rb
# frozen_string_literal: true

class TvController < ApplicationController
  respond_to :html, :json

  def index
    @playlist = !channel.blank? && channel.playlists.active.any? ? channel.playlists.active.first : nil
    @today_playlist = channel.playlists.finalized.where('CAST(start_time AS date) = ?', Time.zone.now.to_date).first || nil

    @active_track = if Track.where(playing: true).joins(:playlist)
                            .where('playlists.channel_id' => (channel ? channel.id : -1)).any?
                      Track.where(playing: true).joins(:playlist)
                           .where('playlists.channel_id' => (channel ? channel.id : -1)).first
                    end
    respond_to do |format|
      format.html
      # format.json do
      #   if @playlist
      #     render json: { online: true, content: render_to_string(partial: 'player.html') }
      #   else
      #     render json: { online: false, content: render_to_string(partial: 'monoscope.html') }
      #   end
      # end
    end
  end

  def banner
    respond_to do |format|
      banner_base = '/szeroka/dh0/www/index_elemei/tv_panel'
      banner = channel.playlists.active.any? ? "#{banner_base}/DHTV_panel_elo.png" : "#{banner_base}/DHTV_panel.png"
      format.html do
        response.headers['Expires'] = 1.day.ago
        response.headers['Cache-Control'] = 'no-cache'
        response.headers['Pragma'] = 'no-cache'
        response.headers['Last-Modified'] = Time.zone.now.strftime('%a, %d %b %Y %T %Z')
        send_data File.read(banner), type: 'image/png', disposition: :inline
      end
    end
  end

  private

  def channel
    @channel ||= Channel.where(domain: request.host).any? ? Channel.where(domain: request.host).first : nil
  end
end

###
# - if @playlist
#          .
#     - else

app/helpers/tv_helper.rb
# frozen_string_literal: true

module TvHelper
end

app/views/tv/_adsense.html.erb
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- Dragonhall2 -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px;"
     data-ad-client="ca-pub-0561270397040036"
     data-ad-slot="8128789862"></ins>
<script>
    (adsbygoogle = window.adsbygoogle || []).push({});
</script>

app/views/tv/_monoscope.html.haml
= image_tag 'monoscope.png', style: 'width: 100%', class: 'monoscope', style: 'display: none'

app/views/tv/_player.html.haml
-# .player(style="display: none;")
.player
  %video#tv_player.video-js.vjs-default-skin.vjs-big-play-centered(controls="controls" preload="none")
    %source{type: 'application/x-mpegURL', src: "https://#{Rails.env.production? ? 'tv.dragonhall.hu' : 'tv.dragonhall.hu'}/live/#{@playlist.channel.stream_path}.m3u8"}

app/views/tv/index.html.haml
%section#tv
  .container
    .box
      .title
      .tabs.is-boxed.is-centered(style="width: 70%; margin: 0 auto")
        %ul
          %li.is-active
            = link_to faw_icon('television', text: 'Lejátszó'), '#', id: 'tabTV'
          %li
            - if Playlist.upcoming.at_today.any?
              = link_to faw_icon('newspaper-o', text: 'Műsor'), '#', id: 'tabProgram'
            - else
              = link_to faw_icon('newspaper-o', text: 'Műsor'), '#', id: 'tabProgram', class: 'has-text-grey-light', disabled: true
      #player.container.is-centered(style="width: 70%; margin-top: 20px; text-align: center;")
        - if @active_track.present? then
          %video#tv_player.video-js.vjs-default-skin.vjs-big-play-centered{controls: 'controls', preload: 'none', poster: image_path('tv_cover.png')}
            %source{type: 'application/x-mpegURL', src: "https://#{Rails.env.production? ? 'tv.dragonhall.hu' : 'tv.dragonhall.hu'}/live/#{@playlist.channel.stream_path}.m3u8"}
        - else
          = image_tag 'monoscope.png', style: 'width: 100%', class: 'monoscope'

      #program.container(style="width: 70%; margin-top: 20px; display: none; text-align: center;")
        -#= image_tag 'http://via.placeholder.com/720x404?text=Program', size: '720x404', style: 'width: 100%'
        - if @today_playlist
          = content_tag :iframe, '', id: 'program_book', src: playlist_tracks_url(playlist_id: @today_playlist.id), style: 'width: 795px; height: 500px; overflow: hidden;', scrolling: 'no', data: { playlist: @today_playlist.id }
          %nav.pagination.is-rounded.is-centered(role="navigation" aria-label="pagination")
            %a.pagination-previous &laquo;
            %a.pagination-next &raquo;
        - else
          #program_book(style="width: 100%; background: #ccc; color: #999;")
            .no-program(style="padding: 200px 0; font-size: 3em;") Bocs, ma nincs adás.

    .box#support
      .has-text-centered
        .hide-mobile#adsense(style="max-width: 913px; margin: 0 auto 20px;")
          = render partial: 'adsense'

      .has-text-centered
        = image_tag('adsense.png', title: 'Azzal is támogathatsz minket, ha rákattintasz a fenti reklámra!', alt: 'Gooogle Adsense', class: 'hide-mobile adsense')
        = link_to image_tag('paypal.png', alt: 'PayPal támogatás'), 'https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=S8SG5VFYVJWDC&source=url', target: '_blank'
        = link_to image_tag('patreon.png', alt: 'Patreon támogatás'), 'https://www.patreon.com/dragonhallplus'

app/views/tv/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_tv_path(@tv)
\|
= link_to 'Back', tvs_path