config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recordings

  get '/tv/index'
  get '/tv/banner'

  get '/tv/current', to: 'tracks#current'

  resources :playlists do
    resources :tracks
  end

  root to: 'tv#index'
end

app/views/layouts/application.html.haml
!!!
%html(lang="hu")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="Content-Type" content="text/html; charset=utf8")
    %meta(name="viewport" content="width=device-width, initial-scale=1")
    %meta{ property: 'og:image', content: image_path('dhtv_social.png') }
    %meta(property="og:description" content="Szinkronba hozzuk az animéket!")
    %meta{ name: 'twitter:image', content: image_path('dhtv_social.png') }
    %meta(name="twitter:description" content="Szinkronba hozzuk az animéket!")


    %title
      = content_for?(:title) ? "#{content_for(:title)} - " : ''
      DragonHall+ TV
    = stylesheet_link_tag :application
    = csrf_meta_tags
    :coffeescript
      if(typeof(window.flowplayer) == 'undefined')
        window.flowplayer = {}

      flowplayer.conf = {
        live: !/recording/.test(window.location.pathname)
        swf: "#{asset_path('flowplayer.swf')}"
      }

    - if GoogleAnalytics.valid_tracker?
      = analytics_init 
      %script{async: true, src: "https://www.googletagmanager.com/gtag/js?id=#{GA.tracker}"}
      %script
        const ga_tracker_id = "#{GA.tracker}"
        :javascript
            window.dataLayer = window.dataLayer || [];
            function gtag(){
                dataLayer.push(arguments);
            }
            gtag('js', new Date());

            gtag('config', ga_tracker_id);
  %body
    -# TODO create helpers for these awful things. fa_icon, navbar_item_link_to, etc.
    %nav.navbar
      .container
        .navbar-brand
          = link_to (image_tag('dhtv_logo.png') + ' DragonHall+ TV'), root_url, class: 'navbar-item'
          .navbar-burger.burger(data-target="navMainMenu")
            %span
            %span
            %span
        #navMainMenu.navbar-menu
          .navbar-start
            -#= link_to((content_tag(:i, '', class: 'fa fa-world') + ' Portál').html_safe, 'http://dragonhall.hu/', class: 'navbar-item')
            -#= link_to((content_tag(:i, '', class: 'fa fa-film') + ' Videótár').html_safe, recordings_url, class: 'navbar-item')
            -#= link_to((content_tag(:i, '', class: 'fa fa-television') + ' TV').html_safe, root_url, class: 'navbar-item')
            = navbar_item_link_to faw_icon('globe', text: 'Portál'), 'http://dragonhall.hu/'
            - if Recording.any?
              = navbar_item_link_to faw_icon('film', text: 'Videótár'), recordings_url
            = navbar_item_link_to faw_icon('television', text: 'TV'), root_url
            = navbar_item_link_to (content_tag(:span, image_tag('tip.png'), class: 'icon') + content_tag(:span, 'Támogatási infók', class: 'has-text-info')), '#', class: 'tip-support'
            = navbar_item_link_to faw_icon('newspaper-o', text: 'Műsorújság'), 'https://dragonhall.hu/dhtvmusor.php'
          .navbar-end
            = navbar_item_link_to content_tag(:span, image_tag('gyik.png'), class: 'icon'), '#', class: 'faq'
            = navbar_item_link_to content_tag(:span, '&sect;'.html_safe, class: 'icon', style: 'font-size: 21px; font-weight: bold;'), '#', class: 'legalcode'
            = navbar_item_link_to content_tag(:span, faw_icon('twitter'), class: 'icon', style: 'color: #00aced'), 'https://twitter.com/dragonhallplus', target: '_blank', rel: 'noopener'
            = navbar_item_link_to content_tag(:span, faw_icon('facebook'), class: 'icon', style: 'font-weight: bold; color: #3b5998'), 'https://www.facebook.com/tv.dragonhall.hu/', target: '_blank', rel: 'noopener'
    = yield
    #legal_modal.modal
      .modal-background
      .modal-card
        %header.modal-card-head
          %p.modal-card-title DragonHall+ TV Szabályzat
          %button.delete(aria-label="Bezárás")
        %section.modal-card-body
          Content
        %footer.modal-card-foot
          %button.button.is-success Megértettem
    = javascript_include_tag :application

app/views/layouts/playlist.html.haml
!!!
%html
  %head
    - content_for(:title) { @title }
    %meta(charset="UTF-8")
    %meta(http-equiv="Content-Type" content="text/html; charset=utf-8")
    %title= content_for?(:title) ? content_for(:title) : "Műsor"
    = csrf_meta_tag

    :css
      @font-face {
        font-family: Discognatehacka;
        src: url(#{asset_path 'Discognatehacka_1.ttf'})
      }

      body {
        background-image: url(#{image_path 'musorhatter.png'});
        font-family: Discognatehacka;
        font-weight: bold;
        color: #1e9edf;
        font-size: 24pt;
      }

    = stylesheet_link_tag :playlists
  %body
    #wrapper
      #heading= content_for?(:title) ? content_for(:title) : 'Műsor'
      #schedule_wrapper
        = yield
        -#%br(style="clear: both;")
      %footer
        = @playlist.start_time.strftime('%Y.%m.%d.')
    = javascript_include_tag :playlists